return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    lazy = false,
    branch = "main",
    config = function()
        require("nvim-treesitter").install({
            "c",
            "cpp",
            "rust",
            "zig",
            "nasm",
            "asm",
            "cuda",
            "glsl",
            "wgsl",
            "hlsl",
            "slang",
            "python",
            "bash",
            "cmake",
            "make",
            "ninja",
            "perl",
            "javascript",
            "typescript",
            "html",
            "css",
            "json",
            "kitty",
            "jsonc",
            "latex",
            "yaml",
            "toml",
            "fish",
            "sql",
            "csv",
            "zsh",
            "dockerfile",
            "ini",
            "lua",
            "vim",
            "vimdoc",
            "query",
            "markdown",
            "markdown_inline",
        })
        -- local config = require("nvim-treesitter.configs")
        -- config.setup({
        --     auto_install = true,
        --     highlight = { enable = true },
        --     indent = { enable = true },
        -- })
    end,
}
